### ISSUE TITLE
Alias command does not run on Slack

### ISSUE THREAD

**Issue by jrstarke** [apsoto/lita-alias#6]
I've installed the **Alias** plugin, and I can add aliases, but when I attempt to use them, nothing happens. Not sure if this is because I'm using Slack or something else. Below you can see that I've added an alias, and I can see it in the list, but when I attempt to use it, nothing happens.

![screen shot 2016-07-07 at 11 35 59 am](https://cloud.githubusercontent.com/assets/46070/16664892/1172dde0-4437-11e6-8fa0-ca000a16f94b.png)

**Comment by apsoto** [comment]
Hey There,

I'm going off memory here, but if I recall the alias does not remove the need for the plugin to recognize the alias as a command, so you still need to prepend a '/' (or whatever other character you use) to trigger commands.

For example, does `/oncall` work ?

**Comment by jaxxstorm** [comment]
Using the `/` doesn't work, having that alias in slack would break all the slack `/` commands.

**Comment by miketheman** [comment]
I think a large part of this is that there's a confusion around what `/` constitutes.
Since Lita allows for:
- multiple chat backends (Slack, IRC, and others)
- a configuration to alias your bot's name to whatever you want

A common approach for IRC is to alias the bot's name to `/` so you can address it as such.

On Slack, however, since that definitely doesn't work, we must use the bot's name `lita` or another alias - I've used `!` - so then commands can be `!help`, `!alias` etc.

In this particular scenario, `lita: oncall` should work, and with an alias: `!oncall` should do the same.

**Comment by apsoto** [comment]
@jaxxstorm let us know if @miketheman's suggestion works so we can close this out.

**Comment by jrstarke** [comment]
This is in the direct message thread with my lita bot. Gave the `!` a try, but it didn't make a difference for me.

<img width="403" alt="screen shot 2016-08-22 at 7 19 10 am" src="https://cloud.githubusercontent.com/assets/46070/17858001/d84dc9f0-6838-11e6-89a4-3da60555ff2c.png">

**Comment by jrstarke** [comment]
Here's me attempting to interact with it in a channel

<img width="303" alt="screen shot 2016-08-22 at 7 23 06 am" src="https://cloud.githubusercontent.com/assets/46070/17858130/4e32ce72-6839-11e6-9f0a-05877ae13712.png">

**Comment by jaxxstorm** [comment]
@jrstarke I figured it out, but it's a pain. Essentially, you need to add the following config option to your `lita_config.rb`:

```
config.robot.alias = '!'
```

I don't think this should be a necessity for using the aliases with slack, tbh

**Comment by miketheman** [comment]
@jaxxstorm I'm glad you figured it out.

In general, this alias plugin takes the path of setting "commands" - these must be directed to the robot, either via direct message or via name/nickname.

A little more on the `command`: https://docs.lita.io/plugin-authoring/handlers/

I don't think we'll entertain changing this, but if you find a reasonable way to implement it, I'm happy to take a look at the code.
